version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fusion_db
      POSTGRES_USER: fusion_user
      POSTGRES_PASSWORD: fusion_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host
    ports:
      - "5173:5173"


volumes:
  postgres_data: