# Generated by Django 5.0.7 on 2024-08-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_alter_budget_owner_alter_transaction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='transaction',
        ),
    ]
